[dev]
  command="yarn develop"
  functions="static/functions"
  targetPort=8000

[build]
  functions="static/functions"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  GATSBY_CPU_COUNT = "2"
  GATSBY_CONCURRENT_DOWNLOAD = "5" 